kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-traffic-from-gateway-to-aved-api
spec:
  podSelector:
    matchLabels:
      app: aved-api-master
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            environment: prod
            name: 264e6f
  policyTypes:
    - Ingress